### ISSUE TITLE
moving data from one computer to another

### ISSUE THREAD

**Issue by sykes140** [ammaarpatel99/pharm-manager#7]
Can I add medicines data on one computer and transfer to another. I understand the files are on chrome specific to the computer in use. How can you access these files.

**Comment by ammaarpatel99** [comment]
The files aren't on chrome, but rather the browser. I.e. you should be able to use it the same way on Chrome, Firefox, Edge, Safari and other browsers. However the saved data is connected to whatever browser you use, so you can't currently move between browsers (and by extension computers). Obviously the easiest way to be use data across browsers and devices is to save it on a server, but I stored it on the device to keep it cheap/free. The only thing I can think of is to store the data in a JSON file that can then be uploaded on another browser/device. I'll have a look into how to do this.

**Comment by ammaarpatel99** [comment]
There is now a backup tab which can be used to backup and restore data. It looks ugly but it works. I would only use it for moving between computers for the time being, although tecnically there shouldn't be any issue with using it for actual backups. Please reply or create a new issue if there are any problems.
